name: Deployment

on:
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    permissions: write-all
    name: linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Update Libs
        run: sudo apt-get install libgtk-3-dev && sudo apt-get install libudev-dev && cargo install cargo-bundle && cargo update
      - name: Install cmake
        # required for hdf5 compilation from source
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
      - name: Build
        run: cargo bundle --release
      #    - name: Compress.
      #      run: ls target/release/bundle/deb && cd target/release/bundle/deb && zip thz-image-explorer.deb.zip *.deb
      - name: Rename
        run: ls target/release/bundle/deb && cd target/release/bundle/deb && mv *.deb thz-image-explorer.deb
      - name: Upload Deb
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/release/bundle/deb/thz-image-explorer.deb
          asset_name: thz-image-explorer-linux_x86.deb
          asset_content_type: binary

  build-macos:
    permissions: write-all
    name: macos x86
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Update Libs
        run: cargo install cargo-bundle && cargo update
      - name: Install cmake
        # required for hdf5 compilation from source
        run: |
          brew install cmake
      - name: Build
        run: cargo bundle --release
      - name: Compress
        run: cd target/release/bundle/osx && ls && zip -r thz-image-explorer.app.zip thz-image-explorer.app/*
      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/release/bundle/osx/thz-image-explorer.app.zip
          asset_name: thz-image-explorer-macos_x86.app.zip
          asset_content_type: binary

  build-macos-arm:
    permissions: write-all
    name: macos arm
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Update Libs
        run: cargo install cargo-bundle && cargo update
      - name: Install cmake
        # required for hdf5 compilation from source
        run: |
         brew install cmake
      - name: Build
        run: cargo bundle --release
      - name: Compress
        run: cd target/release/bundle/osx && ls && zip -r thz-image-explorer.app.zip thz-image-explorer.app/*
      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/release/bundle/osx/thz-image-explorer.app.zip
          asset_name: thz-image-explorer-macos_arm.app.zip
          asset_content_type: binary

  build-windows:
    permissions: write-all
    name: windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Update Libs
        run: cargo install cargo-wix && cargo update
      - name: Install CMake
        # required for hdf5 compilation from source
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
      - name: Verify CMake Installation
        run: cmake --version
      - name: Build
        run: cargo wix
      - name: Compress
        run: cd target/wix && ls && Compress-Archive *.msi thz-image-explorer.msi.zip
      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/wix/thz-image-explorer.msi.zip
          asset_name: thz-image-explorer-windows_x86.msi.zip
          asset_content_type: binary
