name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cmake
        # required for hdf5 compilation from source
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-3-dev
          sudo apt-get install libudev-dev
          sudo apt-get install -y cmake

      - name: Install ALSA development libraries
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Build
        run: cargo build --all --all-features

      - name: Cargo check
        run: cargo check --all --all-features

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all --all-targets --all-features

      - name: Test
        run: cargo test --all --all-features
